##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# Task to check if Namespace, Clusterrolebinding or StorageClass is created
# This task will try for a maximum number of iterations defined in env.retry_count of network.yaml with an interval of
# 35 seconds between each try

# Check if component created without retry
- name: Check {{ component_type }} {{ component_name }} is created (no_retry)
  k8s_info:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: namespace_result_no_retry
  when: 
    - component_type == "Namespace" or component_type == "StorageClass" or component_type == "ClusterRoleBinding"
    - type == "no_retry"

# Check if a component is created with retry
- name: Wait for {{ component_type }} {{ component_name }} (retry)
  k8s_info:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: namespace_result_retry
  retries: "{{ network.env.retry_count }}"
  delay: 35
  until: namespace_result_retry.resources is defined and namespace_result_retry.resources|length > 0
  when: 
    - component_type == "Namespace" or component_type == "StorageClass" or component_type == "ClusterRoleBinding"
    - type is undefined or type == "retry"

# Task to check if ServiceAccount is created without retry
- name: Check {{ component_type }} {{ component_name }} is created (no_retry)
  k8s_info:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: sa_result_no_retry
  when: (component_type == "ServiceAccount" and type == "no_retry")

# Task to check if ServiceAccount is created with retry
- name: Wait for {{ component_type }} {{ component_name }} (retry)
  k8s_info:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: sa_result_retry
  retries: "{{ network.env.retry_count }}"
  delay: 35
  until: sa_result_retry.resources is defined and sa_result_retry.resources|length > 0
  when: (component_type == "ServiceAccount" and (type is undefined or type == 'retry'))

# Consolidate results into the standard "result" fact
- name: Set final result fact
  set_fact:
    result: "{{ 
      namespace_result_no_retry if (namespace_result_no_retry is defined and namespace_result_no_retry.resources is defined) else (
      namespace_result_retry if (namespace_result_retry is defined and namespace_result_retry.resources is defined) else (
      sa_result_no_retry if (sa_result_no_retry is defined and sa_result_no_retry.resources is defined) else (
      sa_result_retry if (sa_result_retry is defined and sa_result_retry.resources is defined) else {'resources': []} ))) 
    }}"
